package fpt.edu.sep490.pilahub.enums;

public enum TransactionType {
    WALLET_TOP_UP,
    WALLET_WITHDRAWAL,
    SUBSCRIPTION_PACKAGE,
    SUBSCRIPTION_PRORATION_REFUND,
    SUBSCRIPTION_UPGRADE,
    REFUND,
    PENALTY,
    BOOKING_COACH,
    BOOKING_COACH_REFUND,
    ORDER,
    VENDOR_PAYOUT,
    PLATFORM_FEE,
    SHIPPING_FEE_THIRD_PARTY,
    SHIPPING_FEE_VENDOR,
    VENDOR_EARNING,
    COURSE
}
